### ISSUE TITLE
[BUGs]自定义称号

### ISSUE THREAD

**Issue by firefairy198** [Moyuyanli/HuYanEconomy#10]
复现步骤：
1.使用称号商店查看可购买的称号（1-小富翁,10000金币 2-测试用的称号2,2金币 3-测试用的称号1,1金币）
2.购买称号 测试用的称号1
3.切换称号 1
4.使用info查看签到信息报错 [bug1]
5.切换称号 0
6.使用info查看签到信息 金币-10000 [bug2]

以下是title.json中的内容：
[
    {
        "templateCode": "测试1",
        "validityPeriod": 365,
        "titleName": "测试用的称号1",
        "price": 1,
        "gradient": false,
        "impactName": false,
        "title": "[测试1]",
        "sColor": "#000000",
        "eColor": "#ffffff"
    },
    {
        "templateCode": "测试2",
        "validityPeriod": 365,
        "titleName": "测试用的称号2",
        "price": 2,
        "gradient": true,
        "impactName": false,
        "title": "[测试2]",
        "sColor": "#CD2990",
        "eColor": "#7FFFD4"
    }
]

以下是报错内容
2024-08-23 06:28:40 I/HuYanEconomy: 壶言经济--个人信息指令
2024-08-23 06:28:41 E/HuYanEconomy: 壶言经济--null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:148)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:26)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:162)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NumberFormatException: For input string: "#0" under radix 16
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:648)
        at java.base/java.lang.Integer.valueOf(Integer.java:963)
        at HuYanEconomy-1.4.0.mirai2.jar//cn.chahuyun.economy.utils.ImageUtil.hexColor(ImageUtil.java:165)
        at HuYanEconomy-1.4.0.mirai2.jar//cn.chahuyun.economy.entity.TitleInfo.getStartColor(TitleInfo.java:73)
        at HuYanEconomy-1.4.0.mirai2.jar//cn.chahuyun.economy.manager.UserManager.customBottom(UserManager.java:250)
        at HuYanEconomy-1.4.0.mirai2.jar//cn.chahuyun.economy.manager.UserManager.getUserInfoImageBase(UserManager.java:206)
        at HuYanEconomy-1.4.0.mirai2.jar//cn.chahuyun.economy.manager.UserManager.getUserInfoImage(UserManager.java:128)
        at HuYanEconomy-1.4.0.mirai2.jar//cn.chahuyun.economy.event.MessageEventListener.onMessage(MessageEventListener.java:87)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 12 more

**Comment by Moyuyanli** [comment]
称号code不建议用中文
