### ISSUE TITLE
插件加载时报错，似乎无法加载钓鱼xlsx表格

### ISSUE THREAD

**Issue by Echomirix** [Moyuyanli/HuYanEconomy#2]
添加机器人QQ号以后加载壶言经济时报错，请问具体是什么原因？
使用系统：**Linux Debian** 
Mirai版本: **v2.16.0**
插件版本: **v0.1.19**

报错如下
```java
2024-08-10 10:41:02 E/HuYanEconomy: cn.hutool.poi.exceptions.POIException: IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream or you haven't provide the poi-ooxml*.jar in the classpath/modulepath - FileMagic: OOXML, having providers: [org.apache.poi.hssf.usermodel.HSSFWorkbookFactory@610f8dd8]
cn.hutool.poi.exceptions.POIException: IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream or you haven't provide the poi-ooxml*.jar in the classpath/modulepath - FileMagic: OOXML, having providers: [org.apache.poi.hssf.usermodel.HSSFWorkbookFactory@610f8dd8]
        at HuYanEconomy-0.1.19.mirai2.jar[private]//cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:148)
        at HuYanEconomy-0.1.19.mirai2.jar[private]//cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:133)
        at HuYanEconomy-0.1.19.mirai2.jar[private]//cn.hutool.poi.excel.ExcelReader.<init>(ExcelReader.java:93)
        at HuYanEconomy-0.1.19.mirai2.jar[private]//cn.hutool.poi.excel.ExcelUtil.getReader(ExcelUtil.java:224)
        at HuYanEconomy-0.1.19.mirai2.jar[private]//cn.hutool.poi.excel.ExcelUtil.getReader(ExcelUtil.java:211)
        at HuYanEconomy-0.1.19.mirai2.jar//cn.chahuyun.economy.plugin.FishManager.reloadFish(FishManager.java:68)
        at HuYanEconomy-0.1.19.mirai2.jar//cn.chahuyun.economy.plugin.FishManager.init(FishManager.java:36)
        at HuYanEconomy-0.1.19.mirai2.jar//cn.chahuyun.economy.HuYanEconomy.onEnable(HuYanEconomy.java:72)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:244)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:393)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:40)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:193)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:360)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.io.IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream or you haven't provide the poi-ooxml*.jar in the classpath/modulepath - FileMagic: OOXML, having providers: [org.apache.poi.hssf.usermodel.HSSFWorkbookFactory@610f8dd8]
        at mirai-administrator-1.4.3.mirai2.jar[shared]//org.apache.poi.ss.usermodel.WorkbookFactory.wp(WorkbookFactory.java:334)
        at mirai-administrator-1.4.3.mirai2.jar[shared]//org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:224)
        at HuYanEconomy-0.1.19.mirai2.jar[private]//cn.hutool.poi.excel.WorkbookUtil.createBook(WorkbookUtil.java:146)
        ... 32 more
```

**Comment by Moyuyanli** [comment]
原因是mirai-administrator也有使用poi，并且还把版本强制固定到他指定的版本，导致我这边报错，我去研究一下解决方案。

**Comment by Moyuyanli** [comment]
[mirai.zip](https://github.com/user-attachments/files/16568586/mirai.zip)
我这边测试无法解决，我去联系一下mirai-administrator的作者，看他那边能不能解决。
你先用这个版本的mirai-administrator，我测试是能正常运行的。

**Comment by Echomirix** [comment]
> [mirai.zip](https://github.com/user-attachments/files/16568586/mirai.zip) 我这边测试无法解决，我去联系一下mirai-administrator的作者，看他那边能不能解决。 你先用这个版本的mirai-administrator，我测试是能正常运行的。

好的，感谢qwq

**Comment by Travellerrr** [comment]
貌似这边还有问题，但是和钓鱼无关（雾


```java
2024-08-10 16:24:31 E/HuYanEconomy: 壶言经济--Exception in EventHandler
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:155)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:26)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:162)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternal.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:148)
        ... 10 more
Caused by: jakarta.persistence.PersistenceException: Converting `org.hibernate.exception.DataException` to JPA `PersistenceException` : JDBC exception executing SQL [select t1_0.userId,t1_0.id,t1_0.dueTime,t1_0.eColor,t1_0.gradient,t1_0.impactName,t1_0.sColor,t1_0.status,t1_0.title,t1_0.type from TitleInfo t1_0 where t1_0.userId=?]
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:165)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:374)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:1073)
        at HuYanEconomy-0.1.19.mirai2.jar[private]//cn.chahuyun.hibernateplus.HibernateFactory.lambda$selectOne$2(HibernateFactory.java:90)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.SessionFactory.fromSession(SessionFactory.java:197)
        at HuYanEconomy-0.1.19.mirai2.jar[private]//cn.chahuyun.hibernateplus.HibernateFactory.selectOne(HibernateFactory.java:88)
        at HuYanEconomy-0.1.19.mirai2.jar//cn.chahuyun.economy.manager.UserManager.getUserInfo(UserManager.java:65)
        at HuYanEconomy-0.1.19.mirai2.jar//cn.chahuyun.economy.manager.SignManager.sign(SignManager.java:59)
        at HuYanEconomy-0.1.19.mirai2.jar//cn.chahuyun.economy.event.MessageEventListener.onMessage(MessageEventListener.java:78)
        ... 14 more
Caused by: org.hibernate.exception.DataException: JDBC exception executing SQL [select t1_0.userId,t1_0.id,t1_0.dueTime,t1_0.eColor,t1_0.gradient,t1_0.impactName,t1_0.sColor,t1_0.status,t1_0.title,t1_0.type from TitleInfo t1_0 where t1_0.userId=?]
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:53)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:253)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:146)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:205)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:85)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:88)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:177)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:443)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.loader.ast.internal.CollectionLoaderSingleKey.load(CollectionLoaderSingleKey.java:121)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:789)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1710)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.collection.spi.AbstractPersistentCollection.lambda$initialize$3(AbstractPersistentCollection.java:617)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.collection.spi.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:813)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:1003)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:989)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:225)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:443)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:113)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:335)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:276)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:571)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363)
        ... 21 more
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "u[QQnumber]"; SQL statement:
select t1_0.userId,t1_0.id,t1_0.dueTime,t1_0.eColor,t1_0.gradient,t1_0.impactName,t1_0.sColor,t1_0.status,t1_0.title,t1_0.type from TitleInfo t1_0 where t1_0.userId=? [22018-214]
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.message.DbException.getJdbcSQLException(DbException.java:506)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.message.DbException.get(DbException.java:212)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.value.ValueStringBase.getLong(ValueStringBase.java:142)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.value.Value.convertToBigint(Value.java:1645)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.value.Value.convertTo(Value.java:1137)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.value.Value.convertTo(Value.java:1003)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.value.Value.compareToNotNullable(Value.java:2631)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.value.Value.compareWithNull(Value.java:2654)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.engine.SessionLocal.compareWithNull(SessionLocal.java:1966)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.expression.condition.Comparison.compare(Comparison.java:250)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.expression.condition.Comparison.getValue(Comparison.java:222)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.expression.Expression.getBooleanValue(Expression.java:332)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.query.Select.isConditionMet(Select.java:449)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.query.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1835)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.result.LazyResult.hasNext(LazyResult.java:78)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.result.FetchedResult.next(FetchedResult.java:34)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.query.Select.queryFlat(Select.java:728)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.query.Select.queryWithoutCache(Select.java:833)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.query.Query.queryWithoutCacheLazyCheck(Query.java:197)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.query.Query.query(Query.java:512)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.query.Query.query(Query.java:475)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.CommandContainer.query(CommandContainer.java:251)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.command.Command.executeQuery(Command.java:190)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:128)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:217)
        ... 54 more
Caused by: java.lang.NumberFormatException: For input string: "u[QQnumber]"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Long.parseLong(Long.java:711)
        at java.base/java.lang.Long.parseLong(Long.java:836)
        at mirai-hibernate-plugin-2.7.1.mirai2.jar[shared]//org.h2.value.ValueStringBase.getLong(ValueStringBase.java:140)
        ... 78 more
```
